steps:
  - label: "create virtualenv"
    command: 
      - python3 -m venv venv
      - source ./venv/bin/activate

  - label: "Install requirements"
    command: pip install -r requirements.txt

  - label: "Run python tests"
    command: python ./test_hello.py



